Move types from `web/common` to `@audius/common`
AudiusProject/audius-client pull request #1618
Opened 2022-07-19 17:20 UTC by nicoback2

### Description
Move models and typeutils from web/common to @audius/common
Will be followed by corresponding mobile and web prs
### Dragons

*Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?*

### How Has This Been Tested?

*Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.*

### How will this change be monitored?

*For features that are critical or could fail silently please describe the monitoring/alerting being added.*

### Feature Flags ###

*Are all new features properly feature flagged? Describe added feature flags.*

2022-07-19 17:21 UTC, dylanjeffers requested changes
awesome!!! could we also remove the existing ones in web, so from diff side it looks like things were moved? that will also require updating imports which is a bit of a pain, so what do you think?

2022-07-19 17:21 UTC, nicoback2 commented
yeah! I was gonna put them in different PRS but I can put it all here

2022-07-19 17:24 UTC, nicoback2 commented
put up the rest! it's a lot of files lol. looks like there's some merge conflicts already, prob just import stuff

2022-07-19 17:44 UTC, audius-infra commented
Preview this change https://demo.audius.co/nkang--common-migration

2022-07-19 20:16 UTC, sliptype approved these changes
This looks good! Do we know what the typecheck errors are about?

2022-07-20 12:57 UTC, audius-infra commented
Preview this change https://demo.audius.co/nkang--common-migration

2022-07-20 14:18 UTC, nicoback2 commented on packages/common/src/models/Cache.ts
> +import { ID, UID } from 'models/Identifiers'
ohh yeah idk, i just did this because i thought that was standard. you're asking about doing `'models/Identifiers'` vs `'./Identifiers'` right?

2022-07-20 15:10 UTC, audius-infra commented
Preview this change https://demo.audius.co/nkang--common-migration

2022-07-20 19:18 UTC, audius-infra commented
Preview this change https://demo.audius.co/nkang--common-migration

2022-07-27 15:29 UTC, audius-infra commented
Preview this change https://demo.audius.co/nkang--common-migration

2022-07-27 16:35 UTC, merged