Fix rewards claim button for aggregate challenges
AudiusProject/audius-client pull request #2671
Opened 2023-01-23 22:53 UTC by dharit-tan

### Description
Fixes bug where rewards claim button was COMMON instead of PRIMARY_ALT for aggregate challenges.

### Dragons

*Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?*

### How Has This Been Tested?

Local web

### How will this change be monitored?

*For features that are critical or could fail silently please describe the monitoring/alerting being added.*

### Feature Flags ###

*Are all new features properly feature flagged? Describe added feature flags.*

2023-01-23 22:55 UTC, rickyrombo approved these changes

2023-01-23 23:05 UTC, piazzatron approved these changes

2023-01-23 23:21 UTC, dharit-tan commented
Ug realized that this component was used elsewhere. Solution is bit ugly but works. Considered splitting into its own component but decided against it. Lmk if suggestions.

2023-01-23 23:24 UTC, sddioulde approved these changes

2023-01-23 23:41 UTC, rickyrombo requested changes
Thinking more on this, we should probably not couple the challenges specific code to the `ButtonWithArrow` component. Let's keep `ButtonWithArrow` generic.

Instead of this, let's pass the buttonType in at the call sites

2023-01-23 23:41 UTC, audius-infra commented
Preview this change https://demo.audius.co/rt-chal-button

2023-01-23 23:49 UTC, rickyrombo approved these changes

2023-01-24 04:21 UTC, audius-infra commented
Preview this change https://demo.audius.co/rt-chal-button

2023-01-24 06:28 UTC, rickyrombo commented on packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
> +        <ButtonWithArrow
at this point, maybe we just axe the `ButtonWithArrow` usage entirely and put the icon in above conditionally on the `hasDisbursed` flag? See convo in slack also

2023-01-24 06:29 UTC, rickyrombo approved these changes
Good with merging as is so we can cherry pick if needed, but I think I'm actually leaning on getting rid of the `ButtonWithArrow` component now (sorry for all the back and forth!)

2023-01-24 17:31 UTC, dharit-tan commented
> Good with merging as is so we can cherry pick if needed, but I think I'm actually leaning on getting rid of the `ButtonWithArrow` component now (sorry for all the back and forth!)

Agree! I'll merge this for now and follow up with a different PR.

2023-01-24 17:31 UTC, merged