Add patch-package to web dev-deps
AudiusProject/audius-client pull request #3383
Opened 2023-05-18 06:49 UTC by rickyrombo

### Description

Needed for #3382 - but just going to use `npx patch-package` on release branch

### Dragons

*Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?*

### How Has This Been Tested?

*Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.*

### How will this change be monitored?

*For features that are critical or could fail silently please describe the monitoring/alerting being added.*

### Feature Flags ###

*Are all new features properly feature flagged? Describe added feature flags.*

2023-05-18 06:51 UTC, raymondjacobson approved these changes

2023-05-18 06:51 UTC, raymondjacobson commented on packages/mobile/ios/Podfile.lock
> +COCOAPODS: 1.12.1
fancy

2023-05-18 07:15 UTC, audius-infra commented
Preview this change https://demo.audius.co/mjp-hotfix-patch-package

2023-05-18 16:22 UTC, dylanjeffers requested changes
lots o changes, mind if i try my hand at it?

2023-05-20 02:41 UTC, audius-infra commented
Preview this change https://demo.audius.co/mjp-hotfix-patch-package

2023-05-25 15:16 UTC, closed without merging