Bump SDK version and change walletapi to auth
AudiusProject/audius-client pull request #3440
Opened 2023-05-25 20:37 UTC by nicoback2

### Description

### Dragons

*Is there anything the reviewer should be on the lookout for? Are there any dangerous changes?*

### How Has This Been Tested?

*Please describe the tests that you ran to verify your changes. Provide repro instructions & any configuration.*

### How will this change be monitored?

*For features that are critical or could fail silently please describe the monitoring/alerting being added.*

### Feature Flags ###

*Are all new features properly feature flagged? Describe added feature flags.*

2023-05-25 20:37 UTC, nicoback2 commented on packages/web/src/services/audius-sdk/audiusSdk.ts
> +          return 'Not implemented'
implementing in [this pr](https://github.com/AudiusProject/audius-client/pull/3396/files), just wanted to minimize the changes here

2023-05-25 20:37 UTC, dylanjeffers requested changes
looks great! mind if i try doing the lock-file change? i think it should ideally be around +100 changes

2023-05-25 20:38 UTC, rickyrombo approved these changes

2023-05-25 20:53 UTC, dylanjeffers approved these changes
okay should be good now diff wise :)

2023-05-25 21:22 UTC, audius-infra commented
Preview this change https://demo.audius.co/nkang--bump-sdk

2023-05-26 17:13 UTC, audius-infra commented
Preview this change https://demo.audius.co/nkang--bump-sdk

2023-05-26 17:21 UTC, merged